### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by ineiti** [c4dt/eid-demo#11]
- [x] @ineiti looks for a meeting with the SICPA team
- [x] @ineiti checks with OFIT for different next steps
- [x] @lanterno writes email to OFIT for input on next steps / why not BBS+? Ask for a date for the android wallet.
- [x] @lanterno prepares questions for meeting with SICPA and writes a short summary here: 2024-05-14

**Comment by ineiti** [comment]
Questions still open:
* what do you think about the W3C VC Data Integrity project?
* what are the cryptographic algorithms used in BBS+ and AnonCreds? Is Anoncreds only RSA, or does it also allow other systems like elliptic curves?
* in general, what are the standards and specifications that are important today? Is https://identity.foundation/ relevant?

**Comment by lanterno** [comment]
### Questions for meeting with SICPA

- General question about the direction on E-ID - What are the technologies that are moving forward, and who is supporting them? 
- Who are the big players in the E-ID space?
- Is BBS+ post-quantum? Are there other ones that are post-quantum?

**Comment by ineiti** [comment]
Closing this in favour of #12
